---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/rojin/virtualP/ProjectAutomation/inventory/hosts.yaml"
        group_file: "/home/rojin/virtualP/ProjectAutomation/inventory/groups.yaml"
        #defaults_file: "/home/rojin/virtualP/ProjectAutomation/inventory/defaults.yaml"

runner:
       plugin: threaded
       options:
            num_workers: 1
